{% set name = "gnuradio-iqbalance" %}
{% set version = "0.38.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitea.osmocom.org/sdr/gr-iqbal/archive/v{{ version }}.tar.gz
  sha256: f06d24143a8b2015494c8a02ba27eb5cdcbdc2495e73435df9ca0b6c2e0ba944
  patches:
    - 0001-Update-for-GNU-Radio-3.9-3.10-compatibility.patch
    - 0002-Use-GNU-Radio-Python-binding-macros.patch
    - 0003-Use-C-std-complex-type-for-portability.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gnuradio-iqbalance', max_pin='x.x') }}
  ignore_run_exports_from:
    # CMakeLists.txt checks for fftw, but doesn't actually link to it
    # (it would if libosmo-dsp was bundled in the package)
    - fftw

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    # cross-compilation requirements
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]

  host:
    - fftw
    - gmp  # [linux]
    - gnuradio-core  # [not gnuradio_extra_pin]
    - gnuradio-core {{ gnuradio_extra_pin }}.*  # [gnuradio_extra_pin]
    - libboost-headers
    - libosmo-dsp
    - pip  # [win]
    - pybind11
    - python
    - numpy

  run:
    - numpy
    - python

test:
  commands:
    # verify that (some) headers get installed
    - test -f $PREFIX/include/gnuradio/iqbalance/api.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\gnuradio\\iqbalance\\api.h exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]

    # verify that GRC blocks get installed
    {% set blocks = ["iqbalance_fix_cc", "iqbalance_optimize_c"] %}

    {% for block in blocks %}
    - test -f $PREFIX/share/gnuradio/grc/blocks/{{ block }}.block.yml  # [not win]
    - if not exist %PREFIX%\\Library\\share\\gnuradio\\grc\\blocks\\{{ block }}.block.yml exit 1  # [win]
    {% endfor %}

  imports:
    - gnuradio.iqbalance

about:
  home: https://gitea.osmocom.org/sdr/gr-iqbal
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GNU Radio module for correcting I/Q imbalance in quadrature receivers
  description: >
    GNU Radio module to correct I/Q imbalance in quadrature receivers.

    It's composed of two main blocks:
    - *fix* : Given a phase and amplitude error, it will correct a complex signal
    - *optimize*: Attempts to auto-detect the phase and amplitude error to feed to
    the fix block above

extra:
  recipe-maintainers:
    - ryanvolz
